# Generated by Django 5.1.6 on 2025-03-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='day_off',
        ),
    ]
