# Generated by Django 5.1.6 on 2025-03-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_date_schedule_day_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='orderTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
